/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ExcCommand {
  name: string
  content: string
}
export declare function runCommands(commands: Array<ExcCommand>): void
